apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: default
spec:
  source:
    repoURL: https://github.com/yourusername/wordpress-k8s.git
    targetRevision: HEAD
    path: kustomize
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress
